### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by domenkozar** [F1bonacc1/process-compose#173]
```
panic: exit status 1

goroutine 37 [running]:
github.com/f1bonacc1/process-compose/src/tui.SetupTui({0xe5d8f0?, 0xc0004055e0?}, {0xc00026ff80, 0x2, 0x0?})
        github.com/f1bonacc1/process-compose/src/tui/view.go:482 +0x156
github.com/f1bonacc1/process-compose/src/cmd.startTui({0xe5d8f0, 0xc0004055e0})
        github.com/f1bonacc1/process-compose/src/cmd/project_runner.go:92 +0x179
created by github.com/f1bonacc1/process-compose/src/cmd.runTui in goroutine 1
        github.com/f1bonacc1/process-compose/src/cmd/project_runner.go:76 +0x65
```

See https://github.com/cachix/devenv/issues/1104

**Comment by F1bonacc1** [comment]
Hi @domenkozar,

Which OS, Version?
Can I have the log and the `compose.yaml`?

**Comment by domenkozar** [comment]
Waiting for more info in https://github.com/cachix/devenv/issues/1104

**Comment by domenkozar** [comment]
process-compose-0.88.0 x86_64-linux

**Comment by F1bonacc1** [comment]
Please try to define TERM:
`export TERM=xterm-256color`
And run again.
